rm(list=ls())
##########Fischer图解#################
#A[i,1]-标注   A[i,2]-旋回顶深    A[i,3]-旋回底深  A[i,4]-符号  A[i,5]-旋回厚度	A[i,6]-偏移	A[i,7]-累积偏移	A[i,8]-旋回数 A[i,9]-层位
#average为旋回厚度的平均值(小数点后4位);sumseq为总的旋回数
#
#读入旋回数据
A<-read.csv("XuanHui.csv")
#读入层位数据
C<-read.csv("CengWei.csv")
#计算总旋回数
sumseq<-length(A[,1])
#计算偏移
A[5]<-A[3]-A[2]
average<-round(mean(A[,5]),4)
A[6]<-A[5]-average
#计算累积偏移
A[sumseq,7]<-A[sumseq,6]
for (i in (sumseq-1):1){
  A[i,7]<-sum(A[sumseq:i,6])
}
#由底至顶写入旋回次序
A[8]<-sumseq:1
#计算每一层位最底部旋回所处数据框位置,1096.5等数字是各个层位的底界
SQmU<-which.min(abs(A[,3]-C[1,2]))
SQmL1<-which.min(abs(A[,3]-C[2,2]))
SQmL2<-which.min(abs(A[,3]-C[3,2]))
SQgU<-which.min(abs(A[,3]-C[4,2]))
SQgL<-which.min(abs(A[,3]-C[5,2]))
#标识各个旋回所属层位
A[1:SQmU,9]<-c("SQmU")
A[(SQmU+1):SQmL1,9]<-c("SQmL1")
A[(SQmL1+1):SQmL2,9]<-c("SQmL2")
A[(SQmL2+1):SQgU,9]<-c("SQgU")
A[(SQgU+1):SQgL,9]<-c("SQgL")
#修正数据框列名
colnames(A)<-c("标注","旋回顶深","旋回底深","符号","旋回厚度","偏移","累积偏移","旋回数","层位")
#将数据框Ａ写入文件
write.csv(A,file="Fischer.csv")
#载入ggplot2包
library("ggplot2")
#计算各个层位顶底
gL_sep<-c(1,A[SQgU+1,8])
gU_sep<-c(A[SQgU,8],A[SQmL2+1,8])
mL2_sep<-c(A[SQmL2,8],A[SQmL1+1,8])
mL1_sep<-c(A[SQmL1,8],A[SQmU+1,8])
mU_sep<-c(A[SQmU,8],A[1,8])
#绘图并另存为png文件
p1<-ggplot(A,aes(旋回数,累积偏移))
p2<-p1+geom_point(aes(colour=层位))+geom_smooth(method="loess",span=0.1,se=TRUE)+labs(title="Fischer图解")+xlab("时间")
p3<-p2+geom_vline(x=c(gL_sep[2],gU_sep[2],mL2_sep[2],mL1_sep[2]),lty=2)
p3+geom_text(x=ave(gL_sep)[1],y=min(A[7]),hjust=0.5,vjust=1,label="SQgL",size=4)+
  geom_text(x=ave(gU_sep)[1],y=min(A[7]),hjust=0.5,vjust=1,label="SQgU",size=4)+
  geom_text(x=ave(mL2_sep)[1],y=min(A[7]),hjust=0.5,vjust=1,label="SQmL2",size=4)+
  geom_text(x=ave(mL1_sep)[1],y=min(A[7]),hjust=0.5,vjust=1,label="SQmL1",size=4)+
  geom_text(x=ave(mU_sep)[1],y=min(A[7]),hjust=0.5,vjust=1,label="SQmU",size=4)
ggsave(file="Fischer.png",dpi=600)